from pathlib import Path
root=Path(__file__).resolve().parent.parent
def change(file,old,new,count=1):
 p=root/file;s=p.read_text(); assert s.count(old)==count,(file,old,s.count(old));p.write_text(s.replace(old,new))
change('local/server.mjs',"import {interpretReading} from './interpret.mjs';","import {interpretReading} from './interpret.mjs';\nimport {interpretWholeChart,resolveReasoningMode} from './whole-chart.mjs';")
change('local/server.mjs',"const startReadingJob=({isMenh,prepared,identity})=>{","const startReadingJob=({isMenh,prepared,identity,reasoningMode='standard'})=>{")
change('local/server.mjs',"const kind=isMenh?'menh':'question',fingerprint=identity.requestFingerprint;","const kind=isMenh?'menh':'question',fingerprint=identity.requestFingerprint+':'+reasoningMode;")
change('local/server.mjs',"const result=isMenh?await interpretMenhReading(prepared,{runner,reviewer,signal:job.controller.signal}):await interpretReading(prepared,{runner,reviewer,signal:job.controller.signal});","const result=isMenh?await interpretMenhReading(prepared,{runner,reviewer,signal:job.controller.signal}):reasoningMode==='whole_chart'?await interpretWholeChart(prepared,{signal:job.controller.signal}):await interpretReading(prepared,{runner,reviewer,signal:job.controller.signal});")
change('local/server.mjs',"job.result=data;job.status='completed';","job.result={...data,reasoningMode};job.status='completed';")
change('local/server.mjs',"const isMenh=isAsyncMenhStart;let prepared,identity;","const isMenh=isAsyncMenhStart;let prepared,identity,reasoningMode;\n       try{reasoningMode=resolveReasoningMode(body.reasoningMode);if(isMenh&&reasoningMode!=='standard')throw new Error('Chế độ này hiện chỉ hỗ trợ Hỏi Việc.');}catch(e){return send(400,{error:e.message});}")
change('local/server.mjs',"const started=startReadingJob({isMenh,prepared,identity});","const started=startReadingJob({isMenh,prepared,identity,reasoningMode});")
change('local/server.mjs',"let prepared,identity;\n       try{\n         prepared=isMenhRead?","let prepared,identity,reasoningMode;\n       try{reasoningMode=resolveReasoningMode(body.reasoningMode);if(isMenhRead&&reasoningMode!=='standard')throw new Error('Chế độ này hiện chỉ hỗ trợ Hỏi Việc.');}catch(e){return send(400,{error:e.message});}\n       try{\n         prepared=isMenhRead?")
change('local/server.mjs',"const result=isMenhRead?await interpretMenhReading(prepared,{runner,reviewer,signal:controller.signal}):await interpretReading(prepared,{runner,reviewer,signal:controller.signal});","const result=isMenhRead?await interpretMenhReading(prepared,{runner,reviewer,signal:controller.signal}):reasoningMode==='whole_chart'?await interpretWholeChart(prepared,{signal:controller.signal}):await interpretReading(prepared,{runner,reviewer,signal:controller.signal});")
change('local/server.mjs',"streaming?res.end(JSON.stringify(data)):send(200,data);","streaming?res.end(JSON.stringify({...data,reasoningMode})):send(200,{...data,reasoningMode});")
change('dist/ai-local.mjs'," const tokenShell=$('ai-token-shell'),connectionIcon=$('ai-connection-icon');"," const tokenShell=$('ai-token-shell'),connectionIcon=$('ai-connection-icon'),reasoningMode=$('reasoning-mode');")
change('dist/ai-local.mjs',"const data=await jobClient.run('/api/read/start',prepared.request,controller.signal,{","const data=await jobClient.run('/api/read/start',{...prepared.request,reasoningMode:reasoningMode?.value||'standard'},controller.signal,{")
change('dist/index.html','            <div class="compact-ai-actions">','            <label class="reasoning-mode-picker" for="reasoning-mode">Cách luận <select id="reasoning-mode" aria-label="Chọn cách luận"><option value="standard">Luận Chuẩn</option><option value="whole_chart">Luận Toàn Bàn</option></select></label>\n            <div class="compact-ai-actions">')
p=root/'dist/styles.css';p.write_text(p.read_text()+"\n.reasoning-mode-picker{display:flex;align-items:center;gap:12px;margin:12px 0;color:#194a39;font-weight:600}.reasoning-mode-picker select{border:1px solid #a9bfb1;background:#fff;padding:9px 12px;border-radius:8px;color:#173e30;font:inherit}\n")
print('WHOLE_CHART_PATCH_OK')
